
apiVersion: v1
kind: Pod
metadata:
  name: pp-data-monitor
spec:
  containers:
    - name: pp-data-monitor
      image: docker.io/kovaleskilab/meep:v3_lightning
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 4Gi
          cpu: 2
      volumeMounts:
        - name: preprocessed-data 
          mountPath: /develop/data/preprocessed_data
  volumes:
    - name: preprocessed-data 
      persistentVolumeClaim:
        claimName: preprocessed-data 

  restartPolicy: Never
