# this is being used as the raw dataset monitor
# kubectl apply -f monitor.yaml
# kubectl exec -it andy-monitor -- /bin/bash

apiVersion: v1
kind: Pod
metadata:
  name: monitor-raw-data
spec:
  containers:
    - name: monitor-raw-data
      image: docker.io/kovaleskilab/deep-optics:v1 
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 4Gi
          cpu: 2
      volumeMounts:
        - name: meep-dataset-v2
          mountPath: /develop/data
  volumes:
    - name: meep-dataset-v2
      persistentVolumeClaim:
        claimName: meep-dataset-v2

