

apiVersion: v1
kind: Pod
metadata:
  name: monitor-training-results
spec:
  containers:
    - name: monitor-training-results
      image: docker.io/kovaleskilab/meep:v3_lightning
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 4Gi
          cpu: 2
      volumeMounts:
        - name: training-results 
          mountPath: /develop/results
  volumes:
    - name: training-results 
      persistentVolumeClaim:
        claimName: training-results 

  restartPolicy: Never
